name: Java CI

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      bypass_copilot:
        default: false
      bypass_codecov:
        default: false
      

jobs:
  build:
    
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew build
    - name: CodeCov
      if: ${{!inputs.bypass_codecov}}
      uses: codecov/codecov-action@v1.0.2
      with:
        token: ${{secrets.CODECOV_UPLOAD_TOKEN}}
    - name: Upload to CoPilot
      if: (github.event_name == 'push' || github.event_name == 'pull_request') && ${{!inputs.bypass_copilot}}
      run: bash <(curl -s https://copilot.blackducksoftware.com/ci/githubactions/scripts/upload)
  validation:
    name: "Validate Gradle Wrapper"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      
